variable "admin_password" {}
variable "admin_username" {}
variable "client_id" {}
variable "client_secret" {}
variable "dev_location" {}
variable "dev_subnet_address_prefixes" {
  default = [""]
}
variable "dev_subnet_name" {}
variable "dev_subnet_name2" {}
variable "dev_vnet_address_space" {
  default = [""]
}
variable "devrg_name" {}
variable "devvnet_name" {}
variable "disk_size_gb" {}
variable "image_offer" {}
variable "image_publisher" {}
variable "image_sku" {}
variable "image_version" {}
variable "os_disk_type" {}
variable "rt_name" {}
variable "subscription_id" {}
variable "tenant_id" {}
variable "udr_address_prefix" {}
variable "udr_name" {}
variable "udr_next_hop_type" {}
variable "vm_instances_count" {}
variable "vm_instances_count1" {}
variable "vm_name" {}
variable "vm_name1" {}
variable "vm_size" {}
variable "udr_next_hop_in_ip_address" {}
